### ISSUE TITLE
Ei tuvasta president Karise häält

### ISSUE THREAD

**Issue by 4nd3r** [infoaed/kryptogramm#2]
Ei tööta :disappointed: 

```
(.venv) ander@m720q:kryptogramm$ ./kryptogramm.py ../kariseh22l.png 
POLE VIST QR-KOODI?
```

QR-kood:
![image](https://user-images.githubusercontent.com/7166727/222530512-3956a738-7bac-435b-928c-c8941468adea.png)

Allikas: Aktuaalne Kaamera, ERR

**Comment by boamaod** [comment]
See QR-koodi lugeja pole just väga hea igasuguste tegelikust elust koodide lugemiseks, tahab neid liiga horisontaalselt ja ei kasuta videost tulevat lisainfot. Mõne muu vahendiga loed selle koodi välja? Muidu pool tundi oli aega kontrollimiseks, seega kahjuks läinud rong vist.

Prooviläbimisel ka oli keeruline videopildist koode välja lugeda, aga [see](https://github.com/infoaed/kryptogramm/blob/main/data/Screenshot%20from%202023-02-16%2010-46-33.png) näiteks pärineb sealt.

**Comment by 4nd3r** [comment]
> Muidu pool tundi oli aega kontrollimiseks, seega kahjuks läinud rong vist.

Nähh, ma lootsin et saab aegade lõpuni :crying_cat_face: 

Olgu.

**Comment by boamaod** [comment]
Kui mõne muu vahendiga kood lugeda, siis on see kõige lihtsam tükkhaaval kopeerida lähtekoodis stringidena [siia](https://github.com/infoaed/kryptogramm/blob/main/kryptogramm.py#L87-L89) ja kõik võiks töötada. Väljad QR-koodis peaks olema samas järjekorras nagu muutujad koodis.
